const NAVIGATOR = {
    START: 'NAVIGATOR_START',
    LOGIN: 'NAVIGATOR_LOGIN',
   };
   const LOGIN_STACK = {
    LOGIN: 'LOGIN',
    GOOGLE_LOGIN: 'GOOGLE_LOGIN',
    REALSTATE_LOGIN: 'REALSTATE_LOGIN',
    REGISTER: 'REGISTER',
    PASSWORD_RECOVERY: 'PASSWORD_RECOVERY',
    EMAIL_SENT: 'EMAIL_SENT',
   };
   export default {
    NAVIGATOR,
    LOGIN_STACK,
   };